[package]
name = "radb_client"
version = "0.1.0"
edition = "2021"
authors = ["Alessandro Crugnola <alessandro.crugnola@gmail.com>"]
description = "adb client for rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.17.1"
anyhow = "1.0.71"
chrono = "0.4.24"
file-mode = "0.1.2"
futures = "0.3.28"
lazy_static = "1.4.0"
log = "0.4.17"
nom = "7.1.3"
props-rs = "0.1.1"
regex = "1.8.1"
string-builder = "0.2.0"
strum_macros = "0.24.3"
time = "0.3.21"
tokio = { version = "1.28.0", features = ["full"] }
tokio-util = { version = "0.7.8", features = ["full"] }
which = "4.4.0"
env_logger = "0.10.0"

[features]
derive = []
