[package]
name = "radb_client"
version = "0.2.0"
edition = "2021"
authors = ["Alessandro Crugnola <alessandro.crugnola@gmail.com>"]
description = "adb client for rust"
license = "MIT"
homepage = "https://github.com/sephiroth74/radb_client"
repository = "https://github.com/sephiroth74/radb_client"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cmd = { path = "/Users/alessandro/Documents/git/sephiroth74/cmd" }
once_cell = "1.17.1"
chrono = "0.4.24"
file-mode = "0.1.2"
lazy_static = "1.4.0"
log = "0.4.17"
nom = "7.1.3"
props-rs = "0.1.1"
regex = "1.8.1"
strum_macros = "0.25.1"
time = "0.3.21"
tokio = { version = "1.28.0", features = ["full"] }
which = "5.0.0"
mac_address = "1.1.5"
uuid = { version = "1.6.1", features = ["v4"] }
arboard = "3.3.0"
image = "0.24.7"
tokio-threadpool = "0.1.18"
num_cpus = "1.16.0"
async-trait = "0.1.74"
thiserror = "1.0.50"
rustix = "0.38.28"
dirs = "5.0.1"
itertools = "0.12.0"
ctrlc = "3.4.1"
crossbeam = "0.8.2"
signal-hook = "0.3.17"
crossbeam-channel = "0.5.9"
threadpool = "1.8.1"

[dev-dependencies]
simple_logger = "4.3.0"
anyhow = "1.0.71"

[features]
default = ["scanner"]
derive = []
scanner = []

