[package]
name = "radb_client"
version = "0.2.9"
edition = "2021"
authors = ["Alessandro Crugnola <alessandro.crugnola@gmail.com>"]
description = "adb client for rust"
license = "MIT"
homepage = "https://github.com/sephiroth74/radb_client"
repository = "https://github.com/sephiroth74/radb_client"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.19.0"
chrono = "0.4.31"
file-mode = "0.1.2"
lazy_static = "1.4.0"
nom = "7.1.3"
props-rs = "0.1.1"
regex = "1.10.2"
strum_macros = "0.25.3"
time = { version = "0.3.31", features = ["macros"] }
which = "5.0.0"
mac_address = "1.1.5"
uuid = { version = "1.6.1", features = ["v4"] }
arboard = "3.3.0"
image = "0.24.7"
num_cpus = "1.16.0"
thiserror = "1.0.51"
rustix = "0.38.28"
dirs = "5.0.1"
itertools = "0.12.0"
crossbeam = "0.8.3"
signal-hook = "0.3.17"
crossbeam-channel = "0.5.10"
threadpool = "1.8.1"
cmd_lib = "1.9.3"
tracing = "0.1.40"
simple-cmd = "0.0.6"
#radb-client-macros = { path = "./macros" }


[dev-dependencies]
indicatif = { version = "0.17.7" }
anyhow = "1.0.71"
ctrlc = "3.4.1"
tracing-subscriber = { version = "0.3.18", features = ["local-time"] }
tracing-appender = "0.2.3"

[features]
default = ["scanner"]
derive = []
scanner = []

[workspace]
#members = ["macros"]

