[package]
name = "radb_client"
version = "0.1.2"
edition = "2021"
authors = ["Alessandro Crugnola <alessandro.crugnola@gmail.com>"]
description = "adb client for rust"
license = "MIT"
homepage = "https://github.com/sephiroth74/radb_client"
repository = "https://github.com/sephiroth74/radb_client"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.17.1"
anyhow = "1.0.71"
chrono = "0.4.24"
file-mode = "0.1.2"
futures = "0.3.28"
lazy_static = "1.4.0"
log = "0.4.17"
nom = "7.1.3"
props-rs = "0.1.1"
regex = "1.8.1"
string-builder = "0.2.0"
strum_macros = "0.25.1"
time = "0.3.21"
tokio = { version = "1.28.0", features = ["full"] }
tokio-util = { version = "0.7.8", features = ["full"] }
which = "5.0.0"
test-env-log = "0.2.8"
mac_address = "1.1.5"
uuid = { version = "1.6.1", features = ["v4"] }
shellexpand = "3.1.0"
arboard = "3.3.0"
image = "0.24.7"
tokio-threadpool = "0.1.18"
rayon = "1.8.0"
tokio-rayon = "2.1.0"
num_cpus = "1.16.0"

[dev-dependencies]
simple_logger = "4.3.0"


[features]
derive = []
